### ISSUE TITLE
future reading?

### ISSUE THREAD

**Issue by MarisaKirisame** [awni/automata_ml#2]
I read the book and is pretty interested. Is there any future reading I should take a look into?

**Comment by awni** [comment]
That was fast!

> Is there any future reading I should take a look into?

It depends what you want to learn about.

- [Weighted Automata Algorithms](https://cs.nyu.edu/~mohri/pub/hwa.pdf) by Mehryar Mohri gives a pretty thorough description of some important operations (compose, determinize, minimize, etc.). This is a pretty general but formal treatment.
- [Differentiable Weighted Finite-State Transducers](https://arxiv.org/abs/2010.01003) is our recent paper on some research applications of automatic differentiation and weighted automata.
- [GTN](https://github.com/gtn-org/gtn) is a software package (I am a co-author) that you can use to implement WFST algorithms with automatic differentiation. This is a good way to supplement the reading.
