### ISSUE TITLE
Typos and comments

### ISSUE THREAD

**Issue by wesbz** [awni/automata_ml#3]
Hi, great work on explaining transducers and their relevance for ML!
Here are a few typos I noticed:

- **page 12**, example 2.1: "_figure 1_" should be "_figure 2.6_"

- **page 17**, caption of figure 3.1, the language of the acceptor should be _{aba}_ instead of _{ab}_

- **page 29**, section 4.2, there's a typo in "_inpuut_".

- **page 35**, there's a typo in "_recurions_".

- **page 43**, in the derivatives of value 1 for graph B: it should be $\frac{dw_2}{dB_2}$ instead of $\frac{dw_2}{dB_1}$

- **page 56**, seems to me like there's a typo in "_let's_" (should have been "lets", I guess?)

- **page 61**, caption figure 6.17: the formula should have been $T=(T_a+T_b+T_c)*$ 

- **page 62**, at the end of the "Repeat tokens" paragraph: "_abbb2 corresponds to abbba_", I guess there's a typo and should have been "_abbb2a_"

Other comments:

- **page 20**, figure 3.8 seems like a hack 😂 having this union as a "unique" acceptor would be less surprising

- **page 21**, section 3.3: "The concatenated graph can be constructed from the original input graphs by wiring start states to accept states." This confused me for a second as it sounds like you're drawing your arc from start states to accept states of the next acceptor, but you clarify it in the next sentence so it was not a big deal.

- **page 30**, example 4.2: Naming the graphs and specifying which composition you are calculating would be nice

**Comment by wesbz** [comment]
I'm also having a look at the notebooks and some figures are missing (as the `notebooks/figures` folder is empty at start). It appears that figures must be fetched from the `figures` folder at the root or added using the `figures/gen_figs.sh` script.

**Comment by awni** [comment]
Wes, thanks so much for the input. I have fixed all of the typos you pointed out and addressed some of your comments. I hope it is ok if I [acknowledge](https://github.com/awni/automata_ml/blob/main/latex/acknowledge.tex) you for the effort.

Regarding the notebooks, I have also updated the [README](https://github.com/awni/automata_ml/blob/main/notebooks/README.md) to explain how to build the figures. The easiest way is to download the archive from my website which comes with the figures pre built, but you can also build them using the script you found.
