### ISSUE TITLE
typos/erros in equations in "Extended examples"

### ISSUE THREAD

**Issue by csukuangfj** [awni/automata_ml#7]
See 
https://github.com/awni/automata_ml/blob/6c3715255aaec41360ff84975adb03948098fa74/latex/extended_examples.tex#L376

and

https://github.com/awni/automata_ml/blob/6c3715255aaec41360ff84975adb03948098fa74/latex/extended_examples.tex#L504

In both equations, it should be `\log p`, not `p`, I think.

**Comment by awni** [comment]
Good catch! Ref commit 665556f1d5b1042cea6aa3ac5206184a3defdaef.
