### ISSUE TITLE
unable to download the pdf

### ISSUE THREAD

**Issue by csukuangfj** [awni/automata_ml#8]
https://awnihannun.com/writing//automata_ml/automata_in_machine_learning.pdf

access denied

<img width="808" alt="Screen Shot 2021-09-02 at 4 19 44 PM" src="https://user-images.githubusercontent.com/5284924/131808675-030598bf-d0a9-4444-84a5-804c33d2ff75.png">

**Comment by csukuangfj** [comment]
The full URL is

http://awnihannun.com.s3-website.us-east-1.amazonaws.com/writing//automata_ml/automata_in_machine_learning.pdf

**Comment by awni** [comment]
Got it, I will fix, thank you!
